In [2]:
# Importing Libraries for parfume project
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import ast 

mens_parfumes = pd.read_csv('ebay_mens_perfume.csv')
womens_parfumes = pd.read_csv('ebay_womens_perfume.csv')

mens_parfumes

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"
...,...,...,...,...,...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,45.0,"45 available / 1,613 sold",1613.0,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,10.0,More than 10 available / 31 sold,31.0,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2.0,2 available / 305 sold,305.0,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2.0,2 available / 22 sold,22.0,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,10.0,More than 10 available / 24 sold,24.0,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [3]:
# Dropping what we don't need for the analysis

mens_parfumes = mens_parfumes.drop(columns=['priceWithCurrency', 'available', 'lastUpdated', 'itemLocation', 'availableText'])

In [4]:
mens_parfumes

,brand,title,type,price,sold
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,116.0
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,48.0
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,27.0
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,159.0
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,156.0
...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,1613.0
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,31.0
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,305.0
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,22.0
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,24.0

In [5]:
# Now, we can start cleanig data

print(mens_parfumes.isnull().sum())

brand    1
title    0
type     3
price    0
sold     6
dtype: int64

In [6]:
# removing null values
mens_parfumes.dropna(subset=['price', 'sold'], inplace=True)
print(mens_parfumes.isnull().sum())

brand    1
title    0
type     3
price    0
sold     0
dtype: int64

In [7]:
#Checking data for the duplicates

print(mens_parfumes.duplicated().sum())

0

In [8]:
print(mens_parfumes['type'].unique())

['Eau de Parfum' 'Eau de Toilette' 'Fragrances' 'Perfume' '/' 'PARFUM'
 'Parfum' 'Concentrated Uncut Pure Body Oil' 'LE PARFUM' 'Eau De Parfum'
 nan 'Unscented' 'Eau de Cologne' '~ THE ONE EAU DE PARFUM SPRAY ~'
 'EXTRAIT DE PARFUM' 'Eau De Toilette' 'Eau De Parfum Intense' 'Pheromone'
 'Aftershave' 'Fragrance & Perfume' 'Eau de Perfume'
 'Jo Malone Cologne Intense Spray' 'Y' 'Gift Sets'
 'Fragrance Rolling Ball' 'Body Spray' 'Eau de toilette'
 'Eau de Toillette'
 'Eau De Toilette, Eau De Parfum, Eau De Parfum Intense' 'Cologne'
 'le parfum' 'Eau de Toilette Intense'
 'Eau de Cologne Spray, Cologne Spray' 'Extrait De Parfum' 'Fine Cologne'
 'Does not apply' 'EDT' 'Extrait de Parfum' 'Editions Parfums'
 'DIOR HOMME COLOGNE' 'Deodorant' 'De Nuit'
 'Eau de Toilette, Cologne Spray' 'Parfum Intense' 'Eau de Parfum Intense'
 'cologne' 'EAU DE COLOGNE SPRAY' 'Roll On' 'Elixir de Parfum' 'Elixir'
 'Various' 'Assorted' 'Eau de Parfum/ Eau de Toilette'
 'Deodorant Body Spray' 'Oil' 'Splash-on' 'edt' 'EDC' 'Car Air Freshener'
 'Eau De Cologne' 'Fragrance Body Spray' 'Body Oil' 'Cologne spray']

In [9]:
mens_parfumes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 994 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   brand   993 non-null    object
 1   title   994 non-null    object
 2   type    991 non-null    object
 3   price   994 non-null    float64
 4   sold    994 non-null    float64
dtypes: float64(2), object(3)
memory usage: 46.6+ KB

In [10]:
# Using ! ChatGPT ! we can autoatizate process of categorizing data using mapping 

# Convert all values in 'type' column to lowercase for consistency
mens_parfumes['type'] = mens_parfumes['type'].str.lower()

# Define a mapping dictionary to categorize the 'type' column
type_mapping = {
    # Eau de Parfum variations
    'eau de parfum': 'Eau de Parfum',
    'parfum': 'Eau de Parfum',
    'le parfum': 'Eau de Parfum',
    'extrait de parfum': 'Eau de Parfum',
    'eau de parfum intense': 'Eau de Parfum',
    'elixir de parfum': 'Eau de Parfum',
    'elixir': 'Eau de Parfum',
    '~ the one eau de parfum spray ~': 'Eau de Parfum',
    'eau de perfume': 'Eau de Parfum',
    'eau de toilette, eau de parfum, eau de parfum intense': 'Eau de Parfum',

    # Eau de Toilette variations
    'eau de toilette': 'Eau de Toilette',
    'eau de toillette': 'Eau de Toilette',
    'edt': 'Eau de Toilette',
    'eau de toilette intense': 'Eau de Toilette',
    'eau de toilette, cologne spray': 'Eau de Toilette',  # Mapping to 'Eau de Toilette'

    # Cologne variations
    'eau de cologne': 'Cologne',
    'cologne': 'Cologne',
    'fine cologne': 'Cologne',
    'cologne spray': 'Cologne',
    'edc': 'Cologne',
    'dior homme cologne': 'Cologne',
    'jo malone cologne intense spray': 'Cologne',
    'eau de cologne spray, cologne spray': 'Cologne',
    'eau de cologne spray': 'Cologne',

    # Perfume variations
    'perfume': 'Perfume',
    'fragrance & perfume': 'Perfume',

    # Body Spray
    'body spray': 'Body Spray',
    'fragrance body spray': 'Body Spray',
    'deodorant body spray': 'Body Spray',

    # Other ambiguous types
    'fragrances': 'Other',
    'pheromone': 'Other',
    'body oil': 'Other',
    'concentrated uncut pure body oil': 'Other',
    'unscented': 'Other',
    'gift sets': 'Other',
    'various': 'Other',
    'assorted': 'Other',
    'does not apply': 'Other',
    'splash-on': 'Other',
    'oil': 'Other',
    'roll on': 'Other',
    'car air freshener': 'Other',
    'fragrance rolling ball': 'Other',
    'y': 'Other',
    'de nuit': 'Other',
    '/': 'Other',
    'eau de parfum/ eau de toilette': 'Eau de Parfum',
    'editions parfums': 'Eau de Parfum',
    'parfum intense': 'Eau de Parfum'
}

# Apply the mapping to categorize the 'type' column
mens_parfumes['type_cleaned'] = mens_parfumes['type'].replace(type_mapping)

# For any unlisted types, mark them as 'Other'
mens_parfumes['type_cleaned'] = mens_parfumes['type_cleaned'].fillna('Other')

# Remove rows where the 'type_cleaned' column is 'Aftershave' or 'Deodorant'
mens_parfumes = mens_parfumes[~mens_parfumes['type_cleaned'].isin(['Aftershave', 'Deodorant'])]

# Check the unique values after cleaning and filtering
print(mens_parfumes['type_cleaned'].unique())

['Eau de Parfum' 'Eau de Toilette' 'Other' 'Perfume' 'Cologne'
 'aftershave' 'Body Spray' 'deodorant']

In [11]:
mens_parfumes

,brand,title,type,price,sold,type_cleaned
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,eau de parfum,84.99,116.0,Eau de Parfum
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,eau de parfum,109.99,48.0,Eau de Parfum
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,eau de toilette,100.00,27.0,Eau de Toilette
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,eau de toilette,44.99,159.0,Eau de Toilette
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,fragrances,16.91,156.0,Other
...,...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,eau de toilette,20.28,1613.0,Eau de Toilette
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,eau de toilette,30.58,31.0,Eau de Toilette
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,eau de toilette,39.99,305.0,Eau de Toilette
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",eau de toilette,9.99,22.0,Eau de Toilette
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,cologne spray,17.49,24.0,Cologne

In [12]:
# After Cleaning we can export to csv for future analysis 

mens_parfumes.to_csv('mens_sales_cleaned_dataset.csv', index=False)